import Papa from 'papaparse';

export const RAW_CSV_DATA = `Timestamp,Score,Enter First and Last Name,"1. Apostles are the first servants of God commissioned to carry out the Matthew 28:19,20 mandate.","2. According to Eph.2:20, Apostles and prophets are the ….",3. Tick the wrong answer. The role of an apostle is to go,4. A false apostle ….. Indicate the wrong answer.,"5. Apostles are always needed to guide, govern, guard and mentor the people of God.",6. Choose the wrong answer. The marks of an apostle are:
21/07/2026 21:30:40,6 / 6,Afeshia ,TRUE,iii. Foundation on which the church is built.,iii. To establish his or her church so people could understand that they are the best apostle in the land.,i. Does not exist.,i. TRUE,"iii. They are popular, well known by the government and are attractive."
21/07/2026 21:32:11,6 / 6,Alicia Noray Bowles ,TRUE,iii. Foundation on which the church is built.,iii. To establish his or her church so people could understand that they are the best apostle in the land.,i. Does not exist.,i. TRUE,"iii. They are popular, well known by the government and are attractive."
21/07/2026 21:29:22,5 / 6,Atiya Williams,TRUE,iii. Foundation on which the church is built.,iii. To establish his or her church so people could understand that they are the best apostle in the land.,iii. Challenges and competes with true apostles for the hearts of the people.,i. TRUE,"iii. They are popular, well known by the government and are attractive."
21/07/2026 21:33:20,5 / 6,"Beverly Selkridge 

",TRUE,iii. Foundation on which the church is built.,iii. To establish his or her church so people could understand that they are the best apostle in the land.,i. Does not exist.,ii. FALSE,"iii. They are popular, well known by the government and are attractive."
21/07/2026 21:32:52,6 / 6,Candy Webb,TRUE,iii. Foundation on which the church is built.,iii. To establish his or her church so people could understand that they are the best apostle in the land.,i. Does not exist.,i. TRUE,"iii. They are popular, well known by the government and are attractive."
21/07/2026 21:31:27,6 / 6,Catherine Vidale ,TRUE,iii. Foundation on which the church is built.,iii. To establish his or her church so people could understand that they are the best apostle in the land.,i. Does not exist.,i. TRUE,"iii. They are popular, well known by the government and are attractive."
21/07/2026 21:30:40,5 / 6,Claudia Cashe,TRUE,iii. Foundation on which the church is built.,ii. To establish the doctrines of the church.,i. Does not exist.,i. TRUE,"iii. They are popular, well known by the government and are attractive."
21/07/2026 21:28:08,6 / 6,Colette Blackburne Joseph ,TRUE,iii. Foundation on which the church is built.,iii. To establish his or her church so people could understand that they are the best apostle in the land.,i. Does not exist.,i. TRUE,"iii. They are popular, well known by the government and are attractive."
21/07/2026 21:30:40,5 / 6,Denise Edwards ,TRUE,iii. Foundation on which the church is built.,iii. To establish his or her church so people could understand that they are the best apostle in the land.,ii. Is facilitated by the devil to confuse people and lead them away from God.,i. TRUE,"iii. They are popular, well known by the government and are attractive."
21/07/2026 21:29:05,5 / 6,Dessel Williams ,TRUE,iii. Foundation on which the church is built.,iii. To establish his or her church so people could understand that they are the best apostle in the land.,ii. Is facilitated by the devil to confuse people and lead them away from God.,i. TRUE,"iii. They are popular, well known by the government and are attractive."
21/07/2026 21:28:06,4 / 6,Diana Selkridge,TRUE,iii. Foundation on which the church is built.,iii. To establish his or her church so people could understand that they are the best apostle in the land.,iii. Challenges and competes with true apostles for the hearts of the people.,i. TRUE,ii. Taking more and more territories for Jesus.
21/07/2026 21:28:54,6 / 6,Felicia Williams ,TRUE,iii. Foundation on which the church is built.,iii. To establish his or her church so people could understand that they are the best apostle in the land.,i. Does not exist.,i. TRUE,"iii. They are popular, well known by the government and are attractive."
21/07/2026 21:31:50,6 / 6,Francisca Swift ,TRUE,iii. Foundation on which the church is built.,iii. To establish his or her church so people could understand that they are the best apostle in the land.,i. Does not exist.,i. TRUE,"iii. They are popular, well known by the government and are attractive."
21/07/2026 21:29:15,4 / 6,Gale agrant,FALSE,iii. Foundation on which the church is built.,iii. To establish his or her church so people could understand that they are the best apostle in the land.,iii. Challenges and competes with true apostles for the hearts of the people.,i. TRUE,"iii. They are popular, well known by the government and are attractive."
21/07/2026 21:27:56,6 / 6,Gillian,TRUE,iii. Foundation on which the church is built.,iii. To establish his or her church so people could understand that they are the best apostle in the land.,i. Does not exist.,i. TRUE,"iii. They are popular, well known by the government and are attractive."
21/07/2026 21:29:29,5 / 6,Ingrid Bonval-Butcher ,TRUE,iii. Foundation on which the church is built.,iii. To establish his or her church so people could understand that they are the best apostle in the land.,ii. Is facilitated by the devil to confuse people and lead them away from God.,i. TRUE,"iii. They are popular, well known by the government and are attractive."
21/07/2026 21:29:54,6 / 6,Javier Marks ,TRUE,iii. Foundation on which the church is built.,iii. To establish his or her church so people could understand that they are the best apostle in the land.,i. Does not exist.,i. TRUE,"iii. They are popular, well known by the government and are attractive."
21/07/2026 21:27:44,6 / 6,Jenetta Pierre,TRUE,iii. Foundation on which the church is built.,iii. To establish his or her church so people could understand that they are the best apostle in the land.,i. Does not exist.,i. TRUE,"iii. They are popular, well known by the government and are attractive."
21/07/2026 21:33:20,6 / 6,Jerzelle Whiteman ,TRUE,iii. Foundation on which the church is built.,iii. To establish his or her church so people could understand that they are the best apostle in the land.,i. Does not exist.,i. TRUE,"iii. They are popular, well known by the government and are attractive."
21/07/2026 21:31:50,6 / 6,Jessica fiddler ,TRUE,iii. Foundation on which the church is built.,iii. To establish his or her church so people could understand that they are the best apostle in the land.,i. Does not exist.,i. TRUE,"iii. They are popular, well known by the government and are attractive."
21/07/2026 21:31:32,6 / 6,Josanne Pompey,TRUE,iii. Foundation on which the church is built.,iii. To establish his or her church so people could understand that they are the best apostle in the land.,i. Does not exist.,i. TRUE,"iii. They are popular, well known by the government and are attractive."
21/07/2026 21:29:25,6 / 6,Jovanka Williams,TRUE,iii. Foundation on which the church is built.,iii. To establish his or her church so people could understand that they are the best apostle in the land.,i. Does not exist.,i. TRUE,"iii. They are popular, well known by the government and are attractive."
21/07/2026 21:30:53,5 / 6,Julie Charles ,TRUE,iii. Foundation on which the church is built.,iii. To establish his or her church so people could understand that they are the best apostle in the land.,i. Does not exist.,i. TRUE,iv. Fearlessness in the face of danger.
21/07/2026 21:31:27,5 / 6,kabrina,TRUE,ii. Building blocks of the church.,iii. To establish his or her church so people could understand that they are the best apostle in the land.,i. Does not exist.,i. TRUE,"iii. They are popular, well known by the government and are attractive."
21/07/2026 21:32:12,6 / 6,Kadijah Daniel,TRUE,iii. Foundation on which the church is built.,iii. To establish his or her church so people could understand that they are the best apostle in the land.,i. Does not exist.,i. TRUE,"iii. They are popular, well known by the government and are attractive."
21/07/2026 21:30:40,4 / 6,Kathleen Joseph-Sandy ,TRUE,iii. Foundation on which the church is built.,iii. To establish his or her church so people could understand that they are the best apostle in the land.,ii. Is facilitated by the devil to confuse people and lead them away from God.,i. TRUE,iv. Fearlessness in the face of danger.
21/07/2026 21:29:03,6 / 6,Kemrolene Opadeyi,TRUE,iii. Foundation on which the church is built.,iii. To establish his or her church so people could understand that they are the best apostle in the land.,i. Does not exist.,i. TRUE,"iii. They are popular, well known by the government and are attractive."
21/07/2026 21:28:32,6 / 6,Kristy Alexander,TRUE,iii. Foundation on which the church is built.,iii. To establish his or her church so people could understand that they are the best apostle in the land.,i. Does not exist.,i. TRUE,"iii. They are popular, well known by the government and are attractive."
21/07/2026 21:31:48,6 / 6,Leslie Inniss ,TRUE,iii. Foundation on which the church is built.,iii. To establish his or her church so people could understand that they are the best apostle in the land.,i. Does not exist.,i. TRUE,"iii. They are popular, well known by the government and are attractive."
21/07/2026 21:30:58,4 / 6,Lynton Pompey ,FALSE,iii. Foundation on which the church is built.,ii. To establish the doctrines of the church.,i. Does not exist.,i. TRUE,"iii. They are popular, well known by the government and are attractive."
21/07/2026 21:32:33,4 / 6,Marlene Walker,TRUE,iii. Foundation on which the church is built.,"i. FIRST, to preach the gospel, teach the babes, plant churches and raise up leaders to do the work of ministry.",iii. Challenges and competes with true apostles for the hearts of the people.,i. TRUE,"iii. They are popular, well known by the government and are attractive."
21/07/2026 21:32:34,6 / 6,Mishael daniel ,TRUE,iii. Foundation on which the church is built.,iii. To establish his or her church so people could understand that they are the best apostle in the land.,i. Does not exist.,i. TRUE,"iii. They are popular, well known by the government and are attractive."
21/07/2026 21:32:56,6 / 6,Natalie Webb Lewis ,TRUE,iii. Foundation on which the church is built.,iii. To establish his or her church so people could understand that they are the best apostle in the land.,i. Does not exist.,i. TRUE,"iii. They are popular, well known by the government and are attractive."
21/07/2026 21:31:23,6 / 6,Niomi Loverne Joseph Marksman,TRUE,iii. Foundation on which the church is built.,iii. To establish his or her church so people could understand that they are the best apostle in the land.,i. Does not exist.,i. TRUE,"iii. They are popular, well known by the government and are attractive."
21/07/2026 21:30:38,5 / 6,Racian Roy,TRUE,iii. Foundation on which the church is built.,iii. To establish his or her church so people could understand that they are the best apostle in the land.,ii. Is facilitated by the devil to confuse people and lead them away from God.,i. TRUE,"iii. They are popular, well known by the government and are attractive."
21/07/2026 21:29:57,6 / 6,Racquel Gumbs ,TRUE,iii. Foundation on which the church is built.,iii. To establish his or her church so people could understand that they are the best apostle in the land.,i. Does not exist.,i. TRUE,"iii. They are popular, well known by the government and are attractive."
21/07/2026 21:30:41,6 / 6,Regina Joseph-Gonzales ,TRUE,iii. Foundation on which the church is built.,iii. To establish his or her church so people could understand that they are the best apostle in the land.,i. Does not exist.,i. TRUE,"iii. They are popular, well known by the government and are attractive."
21/07/2026 21:33:15,3 / 6,Rennie bowles,TRUE,iii. Foundation on which the church is built.,"i. FIRST, to preach the gospel, teach the babes, plant churches and raise up leaders to do the work of ministry.",ii. Is facilitated by the devil to confuse people and lead them away from God.,i. TRUE,ii. Taking more and more territories for Jesus.
21/07/2026 21:31:06,6 / 6,Richard Roberts ,TRUE,iii. Foundation on which the church is built.,iii. To establish his or her church so people could understand that they are the best apostle in the land.,i. Does not exist.,i. TRUE,"iii. They are popular, well known by the government and are attractive."
21/07/2026 21:31:48,6 / 6,Shellon Liddell ,TRUE,iii. Foundation on which the church is built.,iii. To establish his or her church so people could understand that they are the best apostle in the land.,i. Does not exist.,i. TRUE,"iii. They are popular, well known by the government and are attractive."
21/07/2026 21:29:59,6 / 6,Stacey Waithe,TRUE,iii. Foundation on which the church is built.,iii. To establish his or her church so people could understand that they are the best apostle in the land.,i. Does not exist.,i. TRUE,"iii. They are popular, well known by the government and are attractive."
22/07/2026 00:17:25,6 / 6,Susan Spark ,TRUE,iii. Foundation on which the church is built.,iii. To establish his or her church so people could understand that they are the best apostle in the land.,i. Does not exist.,i. TRUE,"iii. They are popular, well known by the government and are attractive."
21/07/2026 21:29:37,5 / 6,Tessa Phipps ,TRUE,iii. Foundation on which the church is built.,iii. To establish his or her church so people could understand that they are the best apostle in the land.,ii. Is facilitated by the devil to confuse people and lead them away from God.,i. TRUE,"iii. They are popular, well known by the government and are attractive."
21/07/2026 21:30:01,5 / 6,TRICIA WORRELL,TRUE,iii. Foundation on which the church is built.,ii. To establish the doctrines of the church.,i. Does not exist.,i. TRUE,"iii. They are popular, well known by the government and are attractive."
21/07/2026 21:31:53,5 / 6,Vanessa,TRUE,iii. Foundation on which the church is built.,iii. To establish his or her church so people could understand that they are the best apostle in the land.,ii. Is facilitated by the devil to confuse people and lead them away from God.,i. TRUE,"iii. They are popular, well known by the government and are attractive."
21/07/2026 21:29:28,5 / 6,Vikash Ramnarace,TRUE,iii. Foundation on which the church is built.,iii. To establish his or her church so people could understand that they are the best apostle in the land.,ii. Is facilitated by the devil to confuse people and lead them away from God.,i. TRUE,"iii. They are popular, well known by the government and are attractive."
21/07/2026 21:33:03,4 / 6,Wendy Woodruffe ,TRUE,iii. Foundation on which the church is built.,iii. To establish his or her church so people could understand that they are the best apostle in the land.,iii. Challenges and competes with true apostles for the hearts of the people.,i. TRUE,"i. Signs, wonders, miracles"
21/07/2026 21:27:37,4 / 6,Whitney Seelochan,TRUE,iii. Foundation on which the church is built.,"i. FIRST, to preach the gospel, teach the babes, plant churches and raise up leaders to do the work of ministry.",ii. Is facilitated by the devil to confuse people and lead them away from God.,i. TRUE,"iii. They are popular, well known by the government and are attractive."
21/07/2026 21:29:43,6 / 6,Zahra Andrews ,TRUE,iii. Foundation on which the church is built.,iii. To establish his or her church so people could understand that they are the best apostle in the land.,i. Does not exist.,i. TRUE,"iii. They are popular, well known by the government and are attractive."`;

export const getDemoAttendance = () => {
  const result = Papa.parse(RAW_CSV_DATA, {
    header: true,
    skipEmptyLines: true,
  });
  return result.data as Record<string, string>[];
};
